[package]
name = "url-shorten"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "server"

[dependencies]
anyhow = "1.0"
async-trait = "0.1.89"
axum = { version = "0.8.7", features = ["macros"] }
tokio = { version = "1.48.0", features = ["full"] }
tower-http = { version = "0.6.8", features = ["fs"] }
tracing = "0.1"
tracing-subscriber = "0.3"
serde = { version = "1.0", features = ["derive"] }
sqlx = { version = "0.8", features = [ "runtime-tokio", "sqlite" ] }
rand = "0.8"
url = "2.5.7"

[dev-dependencies]
http-body-util = "0.1.0"
tower = { version = "0.5.1", features = ["full"] }
serde_json = "1.0"
